name: Submodules update

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Update submodules
        run: git submodule update --init --checkout -f --remote --recursive

      - name: Commit and push updates
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "github-actions"
          git commit -am "Update submodules" && git push || echo "No changes to commit"
